# Dependency: https://github.com/xtekky/gpt4free
import g4f
import pyttsx3
from pynput import keyboard
import time
import random

g4f.logging = True
g4f.check_version = False
print(g4f.version)
print(g4f.Provider.Ails.params)

instructions = "Tell me everything you know about the following topic: "

prompts = [
    "Logic",
    "Pure Mathematics",
    "Applied Mathematics",
    "Fundamental Rules",
    "Mathematical Logic",
    "Theory of Computation",
    "Set Theory",
    "Category Theory",
    "Number Theory",
    "Combinatorics",
    "Real Numbers",
    "Rational Numbers",
    "Natural Numbers",
    "Linear Algebra",
    "Algebra",
    "Graph Theory",
    "Partition Theory",
    "Order Theory",
    "Measure Theory",
    "Differential Geometry",
    "Topology",
    "Complex Analysis",
    "Fractal Geometry",
    "Dynamical Systems",
    "Chaos Theory",
    "Butterfly Effect",
    "Dynamical Systems",
    "Trigonometry",
    "Vector Calculus",
    "Calculus",
    "History of Mathematics",
    "Game Theory",
    "Cryptography",
    "Computer Science",
    "Machine Learning",
    "Optimization",
    "Statistics",
    "Finance",
    "Economics",
    "Engineering",
    "Numerical Analysis",
    "Biomathematics",
    "Mathematical Physics",
    "Mathematical Chemistry",
    "Mathematics",
    "Algebra",
    "Abstract Algebra",
    "Linear Algebra",
    "Equations",
    "Vectors",
    "Matrices",
    "Functions",
    "Inverse",
    "Bijective",
    "Surjective",
    "Injective",
    "Symmetric",
    "Constant",
    "Polinomial",
    "Linear",
    "Quadratic",
    "Modular",
    "Exponential",
    "Logarithmic",
    "Trigonometric",
    "Rational",
    "Calculus",
    "Derivatives",
    "Limits",
    "Arithmetic",
    "Addition",
    "Subtraction",
    "Multiplication",
    "Division",
    "Decimals",
    "Percentages",
    "Fractions",
    "Discrete Mathematics",
    "Logic",
    "Boolean Algebra",
    "Karnaugh Maps",
    "Proofs",
    "Graph Theory",
    "Computational Mathematics",
    "Sets",
    "Euler Diagrams",
    "Venn Diagrams",
    "Complement",
    "Subsets",
    "Union",
    "Intersection",
    "Symmetric difference",
    "Cartesian Product",
    "Power Set",
    "Cardinality",
    "Identity",
    "Number Theory",
    "Perfect Numbers",
    "Complex Numbers",
    "Prime Numbers",
    "Group Theory",
    "Analytic Number Theory",
    "Combinatorics",
    "Combinations",
    "Permutations",
    "Newton Binomial",
    "Pascal Triangle",
    "Probability",
    "Bayes Theorem",
    "Conditioned Probability",
    "Morgan Laws",
    "Independent Events",
    "Fermat and Pascal",
    "Coding Theory",
    "Cryptography",
    "Number Systems",
    "Integers",
    "Natural Numbers",
    "Cardinal Numbers",
    "Infinity",
    "Rational Numbers",
    "Complex Numbers",
    "Game Theory",
    "Dominant strategy",
    "Nash Equilibrium",
    "Zero-Sum Game",
    "Decision-making",
    "Exploiting weaknesses",
    "Expected Value",
    "Resource Usage",
    "Actions",
    "Statistics",
    "Regression",
    "Classification",
    "Standard Deviation",
    "Z-Score",
    "Variance",
    "IQR",
    "Density Curve",
    "Collection, Processing, Presentation",
    "Outlier",
    "Clusters",
    "feature vector",
    "Sample",
    "Population",
    "Trials",
    "Survey, quiz, focus group",
    "Distributions",
    "Normal",
    "Power-law",
    "Erlang",
    "Hypergeometric",
    "Binomial",
    "Geometry",
    "Trigonometry",
    "SOH CAH TOA",
    "Pythagoras Theorem",
    "Radians",
    "Inverse/arc",
    "Triangle Angles",
    "Trigonometric Equations",
    "Matrix Operations",
    "Addition/Subtraction",
    "Multiplication",
    "Square Matrix",
    "Zero Matrix",
    "Transpose",
    "Identity",
    "Inverse",
    "Transformations",
    "Areas",
    "Volumes",
    "Primitives",
    "Vectors",
    "Addition",
    "Subtraction",
    "Dot Product",
    "Cross Product",
    "Projection",
    "Figures",
    "Solids",
    "Intersections",
    "Coordinate Systems",
    "PEMDAS",
    "BODMAS",
    "DMAS",
    "Polyhedra",
    "Polygons",
    "Lines",
    "Points",
    "Triangles",
    "Squares",
    "Pentagons",
    "Hexagons",
    "Octagons",
    "Patterns",
    "Fibonnacci",
    "Factorial",
    "Kaprekar's Constant",
    "Quartic Functions",
    "Quintic Functions",
    "Spherical Geometry",
    "Hyperbolic Geometry",
    "Riemannian Geometry",
    "Non-Euclidean Geometry",
    "Dimensional Analysis",
    "Green's Theorem",
    "Stokes' Theorem",
    "Fourier Series",
    "Fourier Transform",
    "Laplace Transform",
    "Zeta Function",
    "Navier-Stokes Equation",
    "Homomorphisms",
    "Isomorphisms",
    "Rings and Fields",
    "Differential Equations",
    "Partial Differential Equations",
    "Integral Equations",
    "Multivariable Calculus",
    "Genetics and Population Dynamics",
    "Financial Mathematics",
    "Mathematical Biology",
    "Operations Research",
    "Percolation Theory",
    "Mathematical Economics",
    "Algebraic Topology",
    "Differential Topology",
    "Functional Analysis",
    "Operator Theory",
    "Algebraic Geometry",
    "Dynamical Systems and Ergodic Theory",
    "Lie Algebra",
    "Mathematical Logic and Foundations.",
    "Theory of Errors and Least Squares",
    "Catastrophe Theory",
    "Operations Management",
    "Control Theory",
    "Data Science",
    "Mathematical Optimization",
    "Spectral Theory",
    "Combinatorial Optimization",
    "Homological Algebra",
    "Integral Transforms",
    "Convex Analysis",
    "Harmonic Analysis",
    "Bifurcation Theory",
    "Knot Theory",
    "Algebraic Number Theory",
    "Representation Theory",
    "Stochastic Processes",
    "Probability Theory",
    "Queueing Theory",
    "Numerical Linear Algebra",
    "Mathematical Statistics",
    "Galois Theory",
    "Nonlinear Dynamics",
    "Time Series Analysis",
    "Manifold Theory",
    "Algebraic Combinatorics",
    "Model Theory",
    "Algebraic K-Theory",
    "Finite Element Method",
    "Banach Spaces",
    "Calculus of Variations",
    "Mathematical Modeling",
    "Topological Groups",
    "Information Theory",
    "Discrete Optimization",
]

break_program = False
def on_press(key):
    global break_program
    if key.char == 'q':
        print ('Quit.')
        break_program = True
        return False
    
with keyboard.Listener(on_press=on_press) as listener:
    engine = pyttsx3.init()
    
    count = 0
    for i in range(1000):
        random.shuffle(prompts)
        for prompt in prompts:
            count += 1
            print(prompt)

            response = g4f.ChatCompletion.create(
                model="gpt-3.5-turbo",
                messages=[
                  {"role": "user", "content": instructions + prompt}
                ],
            )

            print(response)

            engine.say(response)
            engine.runAndWait()
            time.sleep(15)
            if break_program == True:
                quit()
    listener.join()